<html>
    <head>
        <title>Error - try, catch, finally</title>
    </head>
    <body>
        <script>
            // consol.log("Log 메세지");
            // console.log("안녕하세요?");

            // try {
            //     consol.log("Log Message");
            // } catch (err) {
            //     console.log(err.name);  // ReferenceError
            //     console.log(err.message);   // consol is not defined
            // }
            // console.log("안녕하세요?"); // 실행됨

            // throw를 사용해서 강제로 에러를 발생.
            var x = "";
            try {
                if (x === "") throw "empty";
                var y = x + 3;
                console.log(y);
            } catch (err) {
                console.log(`x is ${err}`);
            } finally {
                console.log("에러 유무와 상관없이 무조건 실행됨.");
            }
        </script>
    </body>
</html>